spring:
  datasource:
    url: jdbc:mysql://114.132.166.29:3306/mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: mall
    password: mall12345
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 114.132.166.29 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: wilson
    timeout: 3000ms # 连接超时时间（毫秒）

minio:
  endpoint: http://114.132.166.29:9000 #MinIO服务所在地址
  bucketName: mall-image #存储桶名称
  accessKey: minio12345 #访问的key
  secretKey: minio12345 #访问的秘钥

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false


management:
  endpoints:
    web:
      exposure:
        include: "*"